# fly.toml app configuration file generated for server-muddy-glade-3958 on 2025-05-06T09:37:30+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'server-muddy-glade-3958'
primary_region = 'fra'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
ASPNETCORE_ENVIRONMENT = "Production"
# Note: sensitive values should be set using fly secrets
AppOptions__PORT = "8080"
AppOptions__WS_PORT = "8181"
AppOptions__REST_PORT = "5000"
AppOptions__Seed = "true"

# Add WebSocket port support
[[services]]
internal_port = 8181
protocol = "tcp"

[[services.ports]]
port = 8181
handlers = ["http"]

# Add REST API port support
[[services]]
internal_port = 5000
protocol = "tcp"

[[services.ports]]
port = 5000
handlers = ["http"]