-- This schema is generated based on the current DBContext. Please check the class Seeder to see.
CREATE TABLE "DeviceConnectionHistory" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "DeviceId" uuid NOT NULL,
    "IsConnected" boolean NOT NULL,
    "LastSeen" timestamp without time zone NOT NULL,
    CONSTRAINT "DeviceConnectionHistory_pkey" PRIMARY KEY ("Id")
);


CREATE TABLE "Devices" (
    "DeviceId" uuid NOT NULL,
    "DeviceName" character varying(100) NOT NULL,
    "IsConnected" boolean NOT NULL DEFAULT FALSE,
    "LastSeen" timestamp without time zone NOT NULL,
    "Updateinterval" integer NOT NULL DEFAULT 30000,
    CONSTRAINT "Devices_pkey" PRIMARY KEY ("DeviceId")
);


CREATE TABLE "SensorData" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Temperature" double precision NOT NULL,
    "Humidity" double precision NOT NULL,
    "AirQuality" double precision NOT NULL,
    "PM25" double precision NOT NULL,
    "DeviceId" uuid NOT NULL,
    "Timestamp" timestamp without time zone NOT NULL,
    CONSTRAINT "SensorData_pkey" PRIMARY KEY ("Id")
);


CREATE UNIQUE INDEX uq_deviceid_timestamp ON "SensorData" ("DeviceId", "Timestamp");


