-- This schema is generated based on the current DBContext. Please check the class Seeder to see.
CREATE TABLE "Devices" (
    "DeviceId" uuid NOT NULL,
    "DeviceName" character varying(100) NOT NULL,
    "IsConnected" boolean NOT NULL DEFAULT FALSE,
    "LastSeen" timestamp without time zone NOT NULL,
    CONSTRAINT "Devices_pkey" PRIMARY KEY ("DeviceId")
);


CREATE TABLE "DeviceConnectionHistory" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "DeviceId" uuid NOT NULL,
    "IsConnected" boolean NOT NULL,
    "LastSeen" timestamp without time zone NOT NULL,
    CONSTRAINT "DeviceConnectionHistory_pkey" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_DeviceConnection_Devices" FOREIGN KEY ("DeviceId") REFERENCES "Devices" ("DeviceId")
);


CREATE TABLE "SensorData" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Temperature" double precision NOT NULL,
    "Humidity" double precision NOT NULL,
    "AirQuality" double precision NOT NULL,
    "PM25" double precision NOT NULL,
    "DeviceId" uuid NOT NULL,
    "Timestamp" timestamp without time zone NOT NULL,
    CONSTRAINT "SensorData_pkey" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TestSensorData_Devices" FOREIGN KEY ("DeviceId") REFERENCES "Devices" ("DeviceId")
);


CREATE INDEX "IX_DeviceConnectionHistory_DeviceId" ON "DeviceConnectionHistory" ("DeviceId");


CREATE UNIQUE INDEX uq_deviceid_timestamp ON "SensorData" ("DeviceId", "Timestamp");


