-- This schema is generated based on the current DBContext. Please check the class Seeder to see.
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'repmgr') THEN
        CREATE SCHEMA repmgr;
    END IF;
END $EF$;


CREATE EXTENSION IF NOT EXISTS repmgr SCHEMA repmgr;


CREATE TABLE "SensorData" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Temperature" double precision NOT NULL,
    "Humidity" double precision NOT NULL,
    "AirQuality" double precision NOT NULL,
    "PM25" double precision NOT NULL,
    "DeviceId" uuid NOT NULL,
    "Timestamp" timestamp without time zone NOT NULL,
    CONSTRAINT "SensorData_pkey" PRIMARY KEY ("Id")
);


