name: Build Verification

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x  # Updated from 7.0.x to match your project
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore