name: Build Verification

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: cd airqualitysystem && dotnet restore
      - name: Build
        run: cd airqualitysystem && dotnet build --no-restore